export type RoutingErrorCode =
  | 'LOCATION_NOT_FOUND'
  | 'NO_STOPS_IN_RANGE'
  | 'NO_TRANSIT_CONNECTION'
  | 'NO_TRANSIT_CONNECTION_IN_SEARCH_WINDOW'
  | 'OUTSIDE_BOUNDS'
  | 'OUTSIDE_SERVICE_PERIOD'
  | 'WALKING_BETTER_THAN_TRANSIT'
  | (string & {});
